Output chat.gif

# Set Shell fish
Set FontSize 18
Set Width 820
Set Height 500
Set Padding 20
Set Framerate 30
Set TypingSpeed 40ms

Hide
Type "cd .."
Enter
Ctrl+L
Show

Type "node index.js"
Enter
Sleep 3s

Type "What is the highest mountain in the world?"
Enter
Sleep 2s

Type "fastest plane?"
Enter
Sleep 2s

Type "2 + 2?"
Enter
Sleep 2s

Type "What other silly and short question can I ask you while making a GIF for my GitHub README.md?"
Enter
Sleep 3s

Type "..."
Enter
Sleep 5s
