Output demo.gif

Set FontSize 18
Set Width 820
Set Height 700
Set Padding 20

Set Framerate 30
Set TypingSpeed 40ms

Hide
Type "cd .."
Enter
Ctrl+L
Show

Type "node index.js"
Enter
Sleep 3s

Type "Short code snippet of fetch function in JS."
Enter
Sleep 4s

Type "List of top 10 most popular Linux distributions."
Enter
Sleep 4s

Type "Table with top 5 programming languages?"
Enter
Sleep 4s

Type "/save all"
Enter
Sleep 4s
